### ISSUE TITLE
 UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 70859: character maps to <undefined>

### ISSUE THREAD

**Issue by rainbow6996** [BOT-HAT/Youtube-First-Comment-Bot#11]
i getting this error, when authentication is successful, how to resolve it?

```
Traceback (most recent call last):
  File "C:\Users\rainbow\Desktop\Nowy folder (4)\Youtube-First-Comment-Bot-master\bot.py", line 76, in <module>
    youtube = get_authenticated_service(args)
  File "C:\Users\rainbow\Desktop\Nowy folder (4)\Youtube-First-Comment-Bot-master\bot.py", line 47, in get_authenticated_service
    doc = f.read()
  File "C:\wszystko\python3.8.4\lib\encodings\cp1250.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 70859: character maps to <undefined>
```

**Comment by JustDhan** [comment]
Same issue

**Comment by nkosinathi-sola** [comment]
@rainbow6996 @JustDhan 

I suggest run your bots in a virtual environment.

A virtual environment helps to keep dependencies required by different projects separate by creating isolated python virtual environments for them. This is one of the most important tools to use. 

Let me know if you still have this error after running on a venv

**Comment by FeelsBadMan1** [comment]
Same issurehere. a venv not solved it.

**Comment by melvas6** [comment]
`with open("youtube-v3-discoverydocument.json", "r", encoding="utf8") as f:`

adding `encoding="utf8" `solved for me
