### ISSUE TITLE
No module named apiclient.discovery

### ISSUE THREAD

**Issue by Libertas007** [BOT-HAT/Youtube-First-Comment-Bot#12]
Hi,
I was trying to run this program, I installed all modules in `requierements.txt` and I run `python bot.py` from command line. And I got an error:
`File "C:\path\to\bot\bot.py", line 6, in <module>
    from apiclient.discovery import build_from_document
ModuleNotFoundError: No module named 'apiclient.discovery'`.

What should I do?

**Comment by ghost** [comment]
Try updating your python / retry downloading all modules from requirements.txt.

**Comment by ghost** [comment]
sudo pip install --upgrade google-api-python-client
it worked for me
