### ISSUE TITLE
Playlist ID parameter can't found !!!

### ISSUE THREAD

**Issue by asutoosh** [BOT-HAT/Youtube-First-Comment-Bot#16]
After I log in with google account .it shows authentication successful.
But then shows

"The playlist identified with the request's <code>playlistId</code> parameter cannot be found".
  Error
What to do?? 
Pls help asap

**Comment by mahisharma-cs** [comment]
The same error I have... any solution?
```
Traceback (most recent call last):
  File "/home/mahi/Documents/languages/python/Youtube-First-Comment-Bot-master/bot.py", line 79, in <module>
    last=lastvideo(youtube,cid)
  File "/home/mahi/Documents/languages/python/Youtube-First-Comment-Bot-master/bot.py", line 70, in lastvideo
    response = request.execute()
  File "/home/mahi/.local/lib/python3.9/site-packages/googleapiclient/_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/mahi/.local/lib/python3.9/site-packages/googleapiclient/http.py", line 935, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 404 when requesting https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=THECHANNELID&alt=json returned "The playlist identified with the request's <code>playlistId</code> parameter cannot be found.". Details: "[{'message': "The playlist identified with the request's <code>playlistId</code> parameter cannot be found.", 'domain': 'youtube.playlistItem', 'reason': 'playlistNotFound', 'location': 'playlistId', 'locationType': 'parameter'}]">
```

**Comment by tigeryu8900** [comment]
@bugtobig @mahisharma-cs Did you use the channel ID instead? The channel ID begins with `UC`. What you want is the uploads playlist ID of the channel, which is the channel ID but with `U` as the second character instead of `C`. For example, the uploads playlist for the channel `UCTkXRDQl0luXxVQrRQvWS6w` is `UUTkXRDQl0luXxVQrRQvWS6w`. I hope that helps.

**Comment by asutoosh** [comment]
@tigeryu8900  It worked for me ..thnks a lot ..❤️❤️❤️

**Comment by mahisharma-cs** [comment]
It is also worked for me. Thanks!! 
Thanks for creating this script.

**Comment by mahisharma-cs** [comment]
It also worked for me. Thanks!!
Thank you for creating this script.
