### ISSUE TITLE
ERROR:      noauth_local_webserver

### ISSUE THREAD

**Issue by nkosinathi-sola** [BOT-HAT/Youtube-First-Comment-Bot#17]
I'm getting the below output after running the bot. Can you perhaps please advise what this implies and how to solve it. 
I'm running the bot on my local.
-----------------------------------------------------------------------------------------------------------------------------
Your browser has been opened to visit:

https://accounts.google.com/o/oauth2/auth?client_id=xxxxxxxxxxxxxxxxaus.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2F&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fyoutube.force-ssl&access_type=offline&response_type=code

If your browser is on a different machine then exit and re-run this
application with the command-line parameter

--noauth_local_webserver

**Comment by nkosinathi-sola** [comment]
Initially it was complaining about URIs not being set on OAuth 2.0. I've tried pointing to http://127.0.0.1:8000 and http://localhost but the above error persists

**Comment by asutoosh** [comment]
Its not an error .
Just copy the link and go to any browser ...
And log in with your given mail id in outh client..
Then after sign in...gave permission to write comments..
Thn return to your terminal..
The bot will start penetratrating...

**Comment by nkosinathi-sola** [comment]
Thanks you @bugtobig 

I tried following the link but then I get:

`**Authorization Error**
Error 400: redirect_uri_mismatch
The redirect URI in the request, http://localhost:8080/, does not match the ones authorized for the OAuth client. To update the authorized redirect URIs`

**Q. Where should point my :** Authorised JavaScript origins and Authorised redirect URIs since I'm running locally?

All my attempts [http://localhost,  http://localhost:8000,  http://127.0.0.1,  http://127.0.0.1:8000 ] are failing

**Comment by nkosinathi-sola** [comment]
@bugtobig I got it mate. I was missing a trailing slash / 😂
