### ISSUE TITLE
Query

### ISSUE THREAD

**Issue by bedfl2016** [BOT-HAT/Youtube-First-Comment-Bot#4]
What do you mean by API etc how do I set this up?

Also are these comments visible to the creator so lets say its like first comment wins will the channel owner see the bots comment as first?

**Comment by tigeryu8900** [comment]
Refer to the [issue](https://github.com/BOT-HAT/Youtube-First-Comment-Bot/issues/8) that I started to set it up. Also, if the program doesn't query Google APIs too many times, it would work (so there's a trade-off between running the script early and setting the interval low), but you need to keep in mind that the bigger the channel, the more likely someone may use this strategy.

Edit: To learn about quotas on how many times you can query, visit [here](https://developers.google.com/analytics/devguides/config/mgmt/v3/limits-quotas#additional_quota).
