### ISSUE TITLE
Playlist ID parameter cannot be found

### ISSUE THREAD

**Issue by iVVaffle** [BOT-HAT/Youtube-First-Comment-Bot#7]
So I'm having this error, where it seems it's looking for a playlist, any ideas what I'm doing wrong?

` <HttpError 404 when requesting https://www.googleapis.com/youtube/v3/playlistItems?alt=json&part=snippet&playlistId=UCGHOni9pO__HNFNg0fj09GQ returned "The playlist identified with the request's <code>playlistId</code> parameter cannot be found.">`

**Comment by tigeryu8900** [comment]
This is not mentioned in the Readme, but change the second letter of the channel id from C to U to make it work.
